-- 10. What is the total revenue generated by films categorized as PG-13

select 
	rating, 
	sum(coalesce(r.amount, 0) + coalesce(r.tax, 0)) as total_revenue_generated
from film f
join rental r on r.film_id = f.film_id
where rating = 'PG-13'
group by rating
